import type { Course } from "./types"

export const courses: Course[] = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    slug: "complete-web-development-bootcamp",
    description: "Learn HTML, CSS, JavaScript, React, Node.js and more to become a full-stack web developer.",
    fullDescription:
      "This comprehensive bootcamp takes you from zero to hero in web development. You will learn everything from basic HTML and CSS to advanced JavaScript frameworks like React, backend development with Node.js, database management, and deployment strategies. By the end of this course, you will have built multiple real-world projects and be ready to land your first developer job.",
    image: "/web-development-coding-laptop.jpg",
    category: "Web",
    level: "Intermediate",
    duration: "10 weeks",
    price: 150, 
    instructor: {
      name: "Mr. Boansi Kyeremateng Collins",
      bio: "Senior Software Engineer at Google with 10+ years of experience teaching web development.",
      avatar: "/professional-woman-portrait.png",
    },
    curriculum: [
      {
        module: "HTML & CSS Fundamentals",
        lessons: ["HTML Structure", "CSS Styling", "Responsive Design", "Flexbox & Grid"],
      },
      {
        module: "JavaScript Essentials",
        lessons: ["Variables & Data Types", "Functions & Scope", "DOM Manipulation", "ES6+ Features"],
      },
      { module: "React Development", lessons: ["Components & Props", "State Management", "Hooks", "Routing"] },
      {
        module: "Backend with Node.js",
        lessons: ["Express.js", "REST APIs", "Database Integration", "Authentication"],
      },
    ],
    whatYouLearn: [
      "Build responsive websites from scratch",
      "Create interactive web applications with React",
      "Develop backend APIs with Node.js",
      "Work with databases like MongoDB and PostgreSQL",
      "Deploy applications to the cloud",
      "Follow industry best practices",
    ],
    prerequisites: ["Basic computer skills", "No coding experience required"],
    enrolledStudents: 15420,
    rating: 4.8,
    reviewCount: 2341,
    language: "English",
    lastUpdated: "2025-12-15",
  },
  {
    id: "2",
    title: "Data Science & Machine Learning",
    slug: "data-science-machine-learning",
    upcoming: true,
    description: "Master Python, data analysis, visualization, and machine learning algorithms.",
    fullDescription:
      "Dive deep into the world of data science and machine learning. This course covers everything from Python programming basics to advanced machine learning algorithms. You will work with real datasets, build predictive models, and learn how to extract insights from complex data. Perfect for aspiring data scientists and analysts.",
    image: "/data-science-visualization-charts.png",
    category: "Data Science",
    level: "Beginner",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Prof. Michael Rodriguez",
      bio: "Former Data Scientist at Netflix, PhD in Machine Learning from Stanford.",
      avatar: "/professional-man-glasses.png",
    },
    curriculum: [
      {
        module: "Python for Data Science",
        lessons: ["Python Basics", "NumPy & Pandas", "Data Cleaning", "Statistical Analysis"],
      },
      { module: "Data Visualization", lessons: ["Matplotlib", "Seaborn", "Plotly", "Dashboard Creation"] },
      {
        module: "Machine Learning",
        lessons: ["Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Feature Engineering"],
      },
      { module: "Deep Learning", lessons: ["Neural Networks", "TensorFlow/Keras", "CNNs", "NLP Basics"] },
    ],
    whatYouLearn: [
      "Python programming for data analysis",
      "Statistical analysis and hypothesis testing",
      "Machine learning algorithm implementation",
      "Deep learning with neural networks",
      "Data visualization best practices",
      "Real-world project deployment",
    ],
    prerequisites: ["Basic programming knowledge", "High school mathematics"],
    enrolledStudents: 8750,
    rating: 4.9,
    reviewCount: 1892,
    language: "English",
    lastUpdated: "2025-11-20",
  },
  {
    id: "3",
    title: "UX/UI Design Masterclass",
    slug: "ux-ui-design-masterclass",
    description: "Learn user experience design, interface design, and prototyping with industry tools.",
    fullDescription:
      "Transform your design skills with this comprehensive UX/UI masterclass. Learn the principles of user-centered design, master tools like Figma and Adobe XD, and build a portfolio that will impress employers. From user research to high-fidelity prototypes, this course covers the entire design process.",
    image: "/ux-ui-design-interface-mockup.jpg",
    category: "UI/UX",
    level: "Beginner",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Emma Thompson",
      bio: "Lead Product Designer at Airbnb with expertise in user-centered design.",
      avatar: "/creative-professional-woman.png",
    },
    curriculum: [
      {
        module: "UX Fundamentals",
        lessons: ["User Research", "Personas", "User Journeys", "Information Architecture"],
      },
      { module: "UI Design Principles", lessons: ["Typography", "Color Theory", "Layout & Grids", "Visual Hierarchy"] },
      { module: "Design Tools", lessons: ["Figma Basics", "Advanced Figma", "Prototyping", "Design Systems"] },
      {
        module: "Portfolio Building",
        lessons: ["Case Studies", "Presentation Skills", "Portfolio Website", "Job Preparation"],
      },
    ],
    whatYouLearn: [
      "Conduct user research and usability testing",
      "Create wireframes and high-fidelity mockups",
      "Master Figma and other design tools",
      "Build accessible and inclusive designs",
      "Create a professional design portfolio",
      "Present and defend design decisions",
    ],
    prerequisites: ["No design experience required", "Creative mindset"],
    enrolledStudents: 6230,
    rating: 4.7,
    reviewCount: 1456,
    language: "English",
    lastUpdated: "2025-12-01",
  },
  {
    id: "4",
    title: "Graphic Design Fundamentals",
    slug: "graphic-design-fundamentals",
    description: "Master Adobe Creative Suite, design principles, and create stunning visual content.",
    fullDescription:
      "Learn the fundamentals of graphic design and master industry-standard tools like Adobe Photoshop, Illustrator, and InDesign. This course covers design theory, typography, color theory, and practical projects including logos, posters, and branding materials. Perfect for aspiring designers and creative professionals.",
    image: "/ux-ui-design-interface-mockup.jpg",
    category: "Graphic Design",
    level: "Beginner",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Maria Gonzalez",
      bio: "Senior Graphic Designer at Adobe with 12 years of experience in branding and visual design.",
      avatar: "/creative-latin-woman.png",
    },
    curriculum: [
      {
        module: "Design Fundamentals",
        lessons: ["Design Principles", "Color Theory", "Typography", "Composition & Layout"],
      },
      { module: "Adobe Photoshop", lessons: ["Interface & Tools", "Photo Editing", "Digital Art", "Effects & Filters"] },
      { module: "Adobe Illustrator", lessons: ["Vector Graphics", "Logo Design", "Illustrations", "Branding"] },
      { module: "Adobe InDesign", lessons: ["Layout Design", "Print Production", "Digital Publishing", "Portfolio Creation"] },
    ],
    whatYouLearn: [
      "Master Adobe Creative Suite tools",
      "Apply design principles and theory",
      "Create professional logos and branding",
      "Design marketing materials and posters",
      "Work with both print and digital media",
      "Build a professional design portfolio",
    ],
    prerequisites: ["No design experience required", "Basic computer skills"],
    enrolledStudents: 4200,
    rating: 4.6,
    reviewCount: 892,
    language: "English",
    lastUpdated: "2025-12-12",
  },
  {
    id: "5",
    title: "Cloud Computing with AWS",
    slug: "cloud-computing-aws",
    description: "Become an AWS certified professional and master cloud architecture.",
    fullDescription:
      "Get certified in Amazon Web Services and become a cloud computing expert. This course prepares you for the AWS Solutions Architect certification while teaching you practical skills in cloud infrastructure, serverless computing, and DevOps practices. Perfect for IT professionals looking to transition to cloud roles.",
    image: "/cloud-computing-aws-servers.jpg",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "James Wilson",
      bio: "AWS Solutions Architect with 15 years of cloud infrastructure experience.",
      avatar: "/professional-man-tech.png",
    },
    curriculum: [
      { module: "AWS Fundamentals", lessons: ["Cloud Concepts", "IAM", "EC2", "S3"] },
      { module: "Networking & Security", lessons: ["VPC", "Security Groups", "Route 53", "CloudFront"] },
      { module: "Databases & Storage", lessons: ["RDS", "DynamoDB", "ElastiCache", "EBS & EFS"] },
      { module: "Serverless & DevOps", lessons: ["Lambda", "API Gateway", "CI/CD", "CloudFormation"] },
    ],
    whatYouLearn: [
      "Design scalable cloud architectures",
      "Implement security best practices",
      "Deploy serverless applications",
      "Optimize cloud costs",
      "Prepare for AWS certification exams",
      "Automate infrastructure with IaC",
    ],
    prerequisites: ["Basic networking knowledge", "Linux command line familiarity"],
    enrolledStudents: 4890,
    rating: 4.8,
    reviewCount: 987,
    language: "English",
    lastUpdated: "2025-12-10",
  },
  {
    id: "6",
    title: "Digital Marketing Fundamentals",
    slug: "digital-marketing-fundamentals",
    description: "Learn SEO, social media marketing, content strategy, and analytics.",
    fullDescription:
      "Master the art and science of digital marketing. This course covers all aspects of online marketing including search engine optimization, pay-per-click advertising, social media strategy, email marketing, and analytics. Learn how to create data-driven campaigns that deliver real results.",
    image: "/digital-marketing-social-media-analytics.jpg",
    category: "Marketing",
    level: "Beginner",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Miss. Alhassan Habibah",
      bio: "Chief Academic Officer with extensive experience in curriculum development and educational technology.",
      avatar: "/habiba.jpeg",
    },
    curriculum: [
      {
        module: "Marketing Foundations",
        lessons: ["Digital Marketing Overview", "Customer Journey", "Brand Strategy", "Market Research"],
      },
      {
        module: "Search & Content",
        lessons: ["SEO Fundamentals", "Keyword Research", "Content Marketing", "Copywriting"],
      },
      {
        module: "Social & Paid Media",
        lessons: ["Social Media Strategy", "Facebook Ads", "Google Ads", "Influencer Marketing"],
      },
      {
        module: "Analytics & Optimization",
        lessons: ["Google Analytics", "A/B Testing", "Conversion Optimization", "ROI Measurement"],
      },
    ],
    whatYouLearn: [
      "Create comprehensive digital marketing strategies",
      "Optimize websites for search engines",
      "Run effective social media campaigns",
      "Analyze marketing data and metrics",
      "Build email marketing funnels",
      "Measure and improve ROI",
    ],
    prerequisites: ["No marketing experience required", "Interest in business and communication"],
    enrolledStudents: 11200,
    rating: 4.6,
    reviewCount: 2103,
    language: "English",
    lastUpdated: "2025-11-25",
  },
  {
    id: "7",
    title: "Mobile App Development with Flutter",
    slug: "mobile-app-development-react-native",
    description: "Build cross-platform mobile apps for iOS and Android withFlutter.",
    fullDescription:
      "Learn to build beautiful, high-performance mobile applications usingFlutter. This course covers everything from setting up your development environment to publishing apps on the App Store and Google Play. Build real projects including a social media app, e-commerce app, and more.",
    image: "/mobile-app-development.png",
    category: "Mobile App",
    level: "Beginner",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Mr. Frederick Owusu Bonsu",
      bio: "Mobile Developer at Meta with expertise inFlutter and cross-platform development.",
      avatar: "/young-professional-developer.jpg",
    },
    curriculum: [
      { module: "React Native Basics", lessons: ["Environment Setup", "Core Components", "Styling", "Navigation"] },
      { module: "State & Data", lessons: ["State Management", "API Integration", "AsyncStorage", "Redux"] },
      {
        module: "Native Features",
        lessons: ["Camera & Media", "Maps & Location", "Push Notifications", "Device APIs"],
      },
      { module: "Deployment", lessons: ["Testing", "Performance", "App Store Submission", "Google Play Submission"] },
    ],
    whatYouLearn: [
      "Build cross-platform mobile apps",
      "Implement native device features",
      "Create beautiful mobile UI/UX",
      "Integrate with backend APIs",
      "Test and debug mobile applications",
      "Publish to App Store and Google Play",
    ],
    prerequisites: ["JavaScript knowledge", "React fundamentals helpful"],
    enrolledStudents: 5670,
    rating: 4.7,
    reviewCount: 1234,
    language: "English",
    lastUpdated: "2025-12-08",
  },
  {
    id: "8",
    title: "Cybersecurity Essentials",
    slug: "cybersecurity-essentials",
    description: "Learn ethical hacking, network security, and security best practices.",
    fullDescription:
      "Protect organizations from cyber threats with this comprehensive cybersecurity course. Learn ethical hacking techniques, network security, cryptography, and incident response. This course prepares you for a career in cybersecurity and relevant industry certifications.",
    image: "/cybersecurity-hacking-security-lock.jpg",
    category: "Cybersecurity",
    level: "Advanced",
    upcoming: true,
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "David Martinez",
      bio: "Former NSA Cybersecurity Analyst, CEH and CISSP certified instructor.",
      avatar: "/security-professional-man.png",
    },
    curriculum: [
      { module: "Security Fundamentals", lessons: ["CIA Triad", "Security Policies", "Risk Assessment", "Compliance"] },
      { module: "Network Security", lessons: ["Firewalls", "IDS/IPS", "VPNs", "Network Monitoring"] },
      {
        module: "Ethical Hacking",
        lessons: ["Reconnaissance", "Vulnerability Assessment", "Penetration Testing", "Reporting"],
      },
      { module: "Incident Response", lessons: ["Threat Detection", "Forensics", "Malware Analysis", "Recovery"] },
    ],
    whatYouLearn: [
      "Identify and assess security vulnerabilities",
      "Perform ethical hacking and penetration testing",
      "Implement network security measures",
      "Respond to security incidents",
      "Understand cryptography and encryption",
      "Prepare for security certifications",
    ],
    prerequisites: ["Networking fundamentals", "Basic Linux/Windows administration"],
    enrolledStudents: 3450,
    rating: 4.9,
    reviewCount: 876,
    language: "English",
    lastUpdated: "2025-12-05",
  },
  {
    id: "9",
    title: "Project Management Professional",
    slug: "project-management-professional",
    description: "Master project management methodologies and prepare for PMP certification.",
    fullDescription:
      "Become a certified project manager with this comprehensive course covering traditional and agile methodologies. Learn to lead projects from initiation to closure, manage stakeholders, and deliver projects on time and within budget. Perfect preparation for the PMP certification exam.",
    image: "/project-management-team.png",
    category: "Business",
    level: "Intermediate",
    duration: "10 weeks",
    price: 150,
    instructor: {
      name: "Jennifer Adams",
      bio: "PMP certified Project Manager with 20 years of experience leading Fortune 500 projects.",
      avatar: "/executive-woman-professional.jpg",
    },
    curriculum: [
      {
        module: "PM Fundamentals",
        lessons: ["Project Life Cycle", "Stakeholder Management", "Project Charter", "Scope Definition"],
      },
      {
        module: "Planning & Execution",
        lessons: ["Work Breakdown Structure", "Schedule Management", "Resource Allocation", "Risk Management"],
      },
      { module: "Agile Methodologies", lessons: ["Scrum Framework", "Kanban", "Sprint Planning", "Agile Metrics"] },
      { module: "PMP Exam Prep", lessons: ["Exam Format", "Practice Questions", "Study Strategies", "Mock Exams"] },
    ],
    whatYouLearn: [
      "Plan and execute projects effectively",
      "Manage project scope, time, and budget",
      "Lead cross-functional teams",
      "Apply Agile and Waterfall methodologies",
      "Handle project risks and issues",
      "Pass the PMP certification exam",
    ],
    prerequisites: ["Some project experience helpful", "Basic business knowledge"],
    enrolledStudents: 7890,
    rating: 4.8,
    reviewCount: 1567,
    language: "English",
    lastUpdated: "2025-11-30",
  },
]

export const categories = [
  "All Categories",
  "Web",
  "Data Science",
  "UI/UX",
  "Graphic Design",
  "Cloud Computing",
  "Marketing",
  "Mobile App",
  "Cybersecurity",
  "Business",
]

export const levels = ["All Levels", "Beginner", "Intermediate", "Advanced"]

export const testimonials = [
  {
    id: 1,
    name: "Amanda Foster",
    role: "Software Engineer at Microsoft",
    avatar: "/professional-woman-smiling.png",
    content:
      "Coltek Academy completely transformed my career. I went from knowing nothing about coding to landing my dream job in just 6 months. The instructors are world-class!",
    course: "Complete Web Development Bootcamp",
  },
  {
    id: 2,
    name: "Robert Chen",
    role: "Data Analyst at Amazon",
    avatar: "/asian-professional-man.png",
    content:
      "The Data Science course gave me the practical skills I needed to transition into analytics. The projects were challenging but incredibly rewarding.",
    course: "Data Science & Machine Learning",
  },
  {
    id: 3,
    name: "Sarah Williams",
    role: "UX Designer at Spotify",
    avatar: "/creative-young-woman.jpg",
    content:
      "I built an amazing portfolio through this course and got multiple job offers. The feedback from instructors was invaluable.",
    course: "UX/UI Design Masterclass",
  },
]

export const stats = [
  { value: "50+", label: "Students Enrolled" },
  { value: "12+", label: "Expert Instructors" },
  { value: null, label: "Courses Available" }, // Dynamic: fetched at runtime
  { value: "95%", label: "Success Rate" },
]
